CREATE (cmd08:DP { id: 'CMD08_DP', step: 1 })
CREATE (cmd08_rule:Rule { name: 'Is this diagnostic has a positive result?', parameter_names: 'result', parameter_types:'String', script:'switch (result) { case \"POSITIVE\": return \"PASSED\"; case \"NEGATIVE\": return \"FAILED\"; case \"PEDNING\": return \"IN_WAIT\"; default: return \"CANCELED\"; }' })
CREATE (cmd08)-[:HAS]->(cmd08_rule)
CREATE (cmd08_rule)-[:PASSED]->(cmd08a)
CREATE (cmd08_rule)-[:FAILED]->(cmd08ds)
CREATE (cmd08_rule)-[:IN_WAIT]->(cmd08w)
CREATE (cmd08_rule)-[:CANCELED]->(cmd08c)
CREATE (cmd08a:A { id: 'CMD08_A', step: 2})
CREATE (cmd08ds:DS { id: 'CMD08_DS', step: 2})
CREATE (cmd08w:STATUS { id: 'CMD08_WAIT', status: 'IN_WAIT'})
CREATE (cmd08c:STATUS { id: 'CMD08_CANCELED', status: 'CANCELED'})
